# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ksonu <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/07/13 15:23:06 by ksonu             #+#    #+#              #
#    Updated: 2017/07/13 15:29:05 by ksonu            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
SRCS = ft_display_file.c

all : build
build:
	gcc -Wall -Wextra -Werror -o $(NAME) $(SRCS)
clean: /bin/rm -f *.o
fclean: clean
	rm -f $(NAME)
